#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sonatype-aether
Version  : 1.13.1
Release  : 3
URL      : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
Source1  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.jar
Source2  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.pom
Source3  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar
Source4  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.pom
Source5  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar
Source6  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.pom
Source7  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
Source8  : https://repo.maven.apache.org/maven2/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.pom
Source9  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom
Source10  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
Source11  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom
Source12  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar
Source13  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.pom
Source14  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
Source15  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom
Source16  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom
Source17  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar
Source18  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.pom
Source19  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
Source20  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom
Source21  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
Source22  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.pom
Source23  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
Source24  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom
Source25  : https://repo1.maven.org/maven2/org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-sonatype-aether-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sonatype-aether package.
Group: Data

%description data
data components for the mvn-sonatype-aether package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.jar
/usr/share/java/.m2/repository/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.pom
/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar
/usr/share/java/.m2/repository/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.pom
/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar
/usr/share/java/.m2/repository/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.pom
/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
/usr/share/java/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom
