#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sonatype-aether
Version  : 1.13.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
Source3  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom
Source4  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
Source5  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom
Source6  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom
Source7  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
Source8  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom
Source9  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
Source10  : https://repo1.maven.org/maven2/org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom
Source11  : https://repo1.maven.org/maven2/org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-sonatype-aether-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sonatype-aether package.
Group: Data

%description data
data components for the mvn-sonatype-aether package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom
/usr/share/java/.m2/repository/org/sonatype/aether/aether/1.13.1/aether-1.13.1.pom
